Add Github Issue Form for bug, documentation and feature
appwrite/demos-for-react pull request #13
Opened 2021-10-02 03:19 UTC by akashgp09

This PR Fixes: #11

2021-10-03 05:30 UTC, lohanidamodar requested changes

2021-10-03 05:30 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/documentation.yaml
> +    id: read-code-of-conduct
Please add this code of conduct option to all the forms. Thank you.

2021-10-04 06:57 UTC, lohanidamodar approved these changes
@akashgp09 Thank you for great work 🙏🏻

2021-10-28 08:21 UTC, merged

2021-10-28 08:22 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)