fix-4274-upgrade-appwrite-to-1.0
appwrite/demos-for-react pull request #16
Opened 2022-10-04 12:08 UTC by omjikush09

## What does this PR do?
upgraded to  appwrite to 1.0 (by upgrading sdk to 10.0.1). 
(Provide a description of what this PR does.)

## Test Plan
verified changes  work  by running React  servers and doing manual testing.
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
Issue
https://github.com/appwrite/appwrite/issues/4274

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-10-05 06:45 UTC, Meldiron commented
@omjikush09 , thanks for the PR! 🤯 Please give us some time to review it.

2022-10-07 16:31 UTC, codercatdev requested changes
@omjikush09 can you please see the comments on the review and fix it? 

Thank you so much for this!!

2022-10-07 16:31 UTC, codercatdev commented on example-auth/src/utils.js
> +  .setEndpoint('http://localhost:8000/v1') // We set the endpoint, change this if your using another endpoint URL.
Let's set this back the the generics `http://localhost/v1` and `ProjectId`.

2022-10-07 16:31 UTC, codercatdev commented on example-cropping/src/App.js
> +    appWrite({ endpoint: 'http://localhost:8000/v1', projectId: '632354c21d497895d2dd' }),
Can we pull in from utils?

2022-10-07 16:31 UTC, codercatdev commented on example-cropping/src/components/SignUp.jsx
> +      await account.create("unique()",email, password);
You can now import `ID` from `appwrite` for helpers like unique.
Then update like below
```
      await account.create(ID.unique(),email, password);
```

2022-10-07 16:31 UTC, codercatdev commented on example-crud/src/actions/index.js
> +      "unique()",
Please pull from ID class, see above comment.

2022-10-07 16:31 UTC, codercatdev commented on example-crud/src/actions/index.js
>  const creatUserDocument = async userData => {
Could we add to the README some basic instructions for creating the correct collections and structure with the new project.

2022-10-07 16:31 UTC, codercatdev commented on example-locale/src/components/YourInfo.js
> +      console.log(res);
Should we leave this?

2022-10-08 18:54 UTC, omjikush09 commented
Done with all requested changes and tested everyProject

2022-10-12 13:55 UTC, codercatdev approved these changes
Thank you!

2022-10-12 13:56 UTC, codercatdev commented
@appwrite/core looks ready to merge

2022-10-31 16:18 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-12-19 21:02 UTC, merged

2022-12-19 21:02 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)